### ISSUE TITLE
add check to see if has mfa at all

### ISSUE THREAD

**Issue by rx294** [mitre/cis-aws-foundations-baseline#17]
https://github.com/mitre/cis-aws-foundations-baseline/blob/95608b301c58587d0f7eac6f7ac04f9cd8171e74/controls/cis-aws-foundations-1.14.rb#L78

**Comment by aaronlippold** [comment]
Actually we should use an or condition here such that we either set it to
the attribute or we send it to the data type that we know will work if it's
an empty array great etc

**Comment by rx294** [comment]
This should get us what we need ... so they dont get an undeserved pass
   describe aws_iam_root_user do
    it { should have_mfa_enabled }
     it { should_not have_virtual_mfa_enabled }
   end
