### ISSUE TITLE
Control Error in control 1.24

### ISSUE THREAD

**Issue by superyarick** [mitre/cis-aws-foundations-baseline#23]
When IAM Policy is 'itself'. In other words if the policy it is validating is the same policy used to run the profile.

```
ERROR 
| Test: Attached PoliciesAWSLambdaTracerAccessExecutionRole-2b5877e2-e9ff-42cc-b1bc-9fc4ba6edde7 
allows full '*:*' privileges? 
| Message: undefined method `keys' for [:Effect,"Allow"]:Array
-- | -- | --
```
POLICIES	arn:aws:iam::823609927185:policy/service-role/AWSLambdaTracerAccessExecutionRole-2b5877e2-e9ff-42cc-b1bc-9fc4ba6edde7	1	2019-05-09T15:07:21+00:00	v1	True	/service-role/	0	ANPA37QX2EYIVMYOMIBHN	AWSLambdaTracerAccessExecutionRole-2b5877e2-e9ff-42cc-b1bc-9fc4ba6edde7	2019-05-09T15:07:21+00:00

aws iam get-policy-version --policy-arn arn:aws:iam::823609927185:policy/service-role/AWSLambdaTracerAccessExecutionRole-2b5877e2-e9ff-42cc-b1bc-9fc4ba6edde7 --version
v1 --query 'PolicyVersion.Document.Statement[?Effect == 'Allow'
&& contains(Resource, '*') && contains (Action, '*')]'

**Comment by rx294** [comment]
@superyarick please check if the fix works for you ... thanks
